specVersion: 1.0.0
name: jax-indexer
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project can be use as a starting point for developing your JAX based SubQuery project.
repository: https://github.com/octalmage/jax-indexer
schema:
  file: ./schema.graphql

network:
  chainId: jax
  endpoint: http://host.docker.internal:26657
  chainTypes: # This is a beta feature that allows support for any Cosmos chain by importing the correct protobuf messages
   jax:
     file: "./proto/jax/tx.proto"
     messages:
      - "MsgStoreCode"
      - "MsgUpdateContract"
      - "MsgUpdateContractAdmin"
dataSources:
  - kind: cosmos/Runtime
    startBlock: 1 
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleStoreCode
          kind: cosmos/MessageHandler
          filter:
            type: "/jax.MsgStoreCode"
        - handler: handleUpdateContract
          kind: cosmos/MessageHandler
          filter:
            type: "/jax.MsgUpdateContract"
        - handler: handleUpdateContractAdmin
          kind: cosmos/MessageHandler
          filter:
            type: "/jax.MsgUpdateContractAdmin"